### ISSUE TITLE
Unable to run on Summit

### ISSUE THREAD

**Issue by atrifan2** [2019-ncovgroup/DrugWorkflows#12] opened 2020-03-26 21:28 UTC
<img width="913" alt="Screen Shot 2020-03-26 at 3 17 46 PM" src="https://user-images.githubusercontent.com/31902227/77698545-d0ed5a80-6f7e-11ea-9f9b-2d52419d1687.png">

**Comment by lee212** [comment] 2020-04-02 14:56
The error caused by `.bash_profile` as it affects the bootstrapping of radical cybertools.

After `cd $MEMBERWORK` is separated from the profile, in this particular case, the error is not seen. Can we close this?

**Comment by lee212** [comment] 2020-04-15 15:14
I will close this for now. Open again if it persists.

**Closed as completed by lee212** 2020-04-15 15:14 UTC
Labels: workflow2
